import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Head from "@/app/head";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${outfit.className}`} lang="en" suppressHydrationWarning>
      <Head />
      <body>
        <ThemeProvider defaultTheme="dark" attribute="class" enableSystem disableTransitionOnChange>
          <Navbar path={""} />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
